//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic5.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        public long idUser { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string login { get; set; }
        [Required]
        [StringLength (256, MinimumLength = 8)]
        public string password { get; set; }
        [Required]
        public long employeeData { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
